### ISSUE TITLE
Control graphics memory usage

### ISSUE THREAD

**Issue by udemegane** [nv-tlabs/datasetGAN_release#2]
I got a cuda OOM while running train_interpreter, I found a variable "batch_size" in train_interpreter.py but changing it doesn't seem to help, can I limit the memory usage?(For example, from the json config) I have a 2080ti board with 11GB of GMEM. 
Thank you.

`Opt {'exp_dir': 'model_dir/face_34', 'category': 'face', 'debug': False, 'dim': [512, 512, 5088], 'deeplab_res': 512, 'number_class': 34, 'testing_data_number_class': 34, 'max_training': 16, 'stylegan_ver': '1', 'annotation_data_from_w': False, 'annotation_mask_path': './dataset_release/annotation/training_data/face_processed', 'testing_path': './dataset_release/annotation/testing_data/face_34_class', 'average_latent': './dataset_release/training_latent/face_34/avg_latent_stylegan1.npy', 'annotation_image_latent_path': './dataset_release/training_latent/face_34/latent_stylegan1.npy', 'stylegan_checkpoint': './dataset_release/stylegan_pretrain/karras2019stylegan-ffhq-1024x1024.for_g_all.pt', 'model_num': 10, 'upsample_mode': 'bilinear'}
/home/udemegane/anaconda3/envs/dataset/lib/python3.7/site-packages/torch/nn/functional.py:2973: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train_interpreter.py", line 578, in <module>
    main(opts)
  File "train_interpreter.py", line 446, in main
    all_feature_maps_train_all, all_mask_train_all, num_data = prepare_data(args, palette)
  File "train_interpreter.py", line 403, in prepare_data
    return_upsampled_layers=True, use_style_latents=args['annotation_data_from_w'])
  File "../utils/utils.py", line 94, in latent_to_image
    affine_layers_upsamples = torch.FloatTensor(1, number_feautre, dim, dim).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 4.97 GiB (GPU 0; 10.76 GiB total capacity; 7.61 GiB already allocated; 2.33 GiB free; 7.65 GiB reserved in total by PyTorch)`

**Comment by arieling** [comment]
Thank you for pointing this out.  We updated the exp files to include batch size variable.
you can modify it here now 
https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/experiments/car_20.json#L3

All results in our paper are based on 32G NVIDIA Tesla V100. Checkpoints will be released soon.

**Comment by udemegane** [comment]
Thanks for your comment.
As noted earlier, changing the batch size does not solve this problem. cuda oom occurs before training, during data prep.
The output resolution for this code is fixed at 512x512 and cannot be easily changed.

**Comment by arieling** [comment]
you may try cat class. the one with 256* 256 res
https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/experiments/cat_16.json#L6

**Comment by udemegane** [comment]
I  tried it on a cat class and the gmem consumption was about 9GB and it worked on my 2080ti.Thanks for your efforts!

**Comment by gwang-kim** [comment]
Thanks for the questions and answers.  @arieling, so isn't it possible to reduce the GPU usage when using the model with 512x512 images by changing the batch size or other methods?

**Comment by arieling** [comment]
you can set a breakpoint at https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L402 and see if it goes through. this is the line pass through styelgan and gather features

**Comment by gwang-kim** [comment]
I got it Thx!
